version: 2.1

workflows:
  django-react-cypress-tests:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: docker:20.10.14-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: | 
            apk add --no-cache py-pip
            apk add docker-compose
      - run:
          name: Docker compose build and up
          command: |
            docker-compose -f docker-compose.test.yml up -d
      - run:
          name: Docker frontend test
          command: |
            docker-compose -f docker-compose.test.yml run frontend npm test -- --watchAll=false
      - run:
          name: Docker backend test
          command: |
            docker-compose -f docker-compose.test.yml run backend python manage.py test
      - run:
          name: Docker end-to-end cypress test
          command: |
            docker-compose -f docker-compose.test.yml run cypress cypress run

      