version: 2.1
orbs:
  python: circleci/python@1.2

workflows:
  django-react-tests:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8-node
      - image: cypress/base:14.15.0
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: media_review_app_test
          POSTGRES_PASSWORD: 1234
      
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

      - run:
          name: python version
          command: python --version
      - run:
          name: node version
          command: node --version