version: 2.1

workflows:
  django-react-cypress-tests_heroku-deploy:
    jobs:
      - build
jobs:
  build:
    machine: true
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      
      - run:
          name: Build docker frontend
          command: |
              docker build -t memoryinject/frontend-test -f ./compose/local/frontend/Dockerfile .
      - run:
          name: Run frontend test with docker
          command: docker run -it -v $PWD/frontend:/app memoryinject/frontend-test npm test -- --watchAll=false 
