version: 2

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2
  # Invoke the heroku orb
  heroku: circleci/heroku@1.2.6

workflows:
  django-react-cypress-tests_heroku-deploy:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/python:3.8-node

    steps:
      - checkout
      - run:
          name: Build docker frontend
          command: |
              docker build -t memoryinject/frontend-test -f ./compose/local/frontend/Dockerfile .
      - run:
          name: Run frontend test with docker
          command: docker run -it -v $PWD/frontend:/app memoryinject/frontend-test npm test -- --watchAll=false 
      - setup_remote_docker:
          version: 20.10.14