version: 2.1

workflows:
  django-react-cypress-tests_heroku-deploy:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: cimg/python:3.8-node
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      
      - run:
          name: Build docker frontend
          command: |
              docker build -t memoryinject/frontend-test -f ./compose/local/frontend/Dockerfile .
      - run:
          name: Run docker commands
          command: |
              docker run -it -v $PWD/frontend:/app memoryinject/frontend-test ls