version: 2.1

workflows:
  django-react-cypress-tests_heroku-deploy:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: docker:20.10.14-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: | 
            apk add --no-cache py-pip
            apk add docker-compose
      - run:
          name: Docker compose up
          command: |
            docker-compose -f docker-compose.test.yml up -d
      - run:
          name: Run tests
          command: |
            docker-compose exec -it frontend npm test -- --watchAll=false