version: 2.1

workflows:
  django-react-cypress-tests_heroku-deploy:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: | 
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d
            docker-compose exec -it frontend npm test -- --watchAll=false