version: 2.1
workflows:
  django-react-tests:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cypress/base:14.15.0
        environment:
          # this enables colors in the output
          TERM: xterm
      - image: cimg/python:3.8
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: media_review_app_test
          POSTGRES_PASSWORD: 1234
      
    steps:
      - checkout
      - run:
          name: python version
          command: python --verion

      - run:
          name: install packages frontend
          command: |
            node --version
            ls
            cd frontend