export const ANNOTATION_SET_ACTIVE = 'ANNOTATION_SET_ACTIVE';
export const ANNOTATION_DRAWABLE_TYPE = 'ANNOTATION_DRAWABLE_TYPE';
export const ANNOTATION_IS_EMPTY = 'ANNOTATION_IS_EMPTY';
export const ANNOTATION_SET_COLOR = 'ANNOTATION_SET_COLOR';

export const ANNOTATION_IMAGE_EXPORT = 'ANNOTATION_IMAGE_EXPORT'
export const ANNOTATION_IMAGE_LOADING = 'ANNOTATION_IMAGE_LOADING'
export const ANNOTATION_IMAGE_SUCCESS = 'ANNOTATION_IMAGE_SUCCESS'
export const ANNOTATION_IMAGE_FAIL = 'ANNOTATION_IMAGE_FAIL'
export const ANNOTATION_IMAGE_RESET = 'ANNOTATION_IMAGE_RESET'
