export const ANNOTATION_SET_ACTIVE = 'ANNOTATION_SET_ACTIVE';
export const ANNOTATION_DRAWABLE_TYPE = 'ANNOTATION_DRAWABLE_TYPE';
export const ANNOTATION_IS_EMPTY = 'ANNOTATION_IS_EMPTY';
export const ANNOTATION_SET_COLOR = 'ANNOTATION_SET_COLOR';

