export const ASSET_CREATE_REQUEST = 'ASSET_CREATE_REQUEST';
export const ASSET_CREATE_SUCCESS = 'ASSET_CREATE_SUCCESS';
export const ASSET_CREATE_FAIL = 'ASSET_CREATE_FAIL';
export const ASSET_CREATE_RESET = 'ASSET_CREATE_RESET';
