export const COLLABORATOR_LIST_GET = 'COLLABORATOR_LIST_GET';
export const COLLABORATOR_LIST_RESET = 'COLLABORATOR_LIST_RESET';

export const COLLABORATOR_DETAILS_GET = 'COLLABORATOR_DETAILS_GET';
export const COLLABORATOR_DETAILS_RESET = 'COLLABORATOR_DETAILS_RESET';

export const COLLABORATOR_UI_SHOW = 'COLLABORATOR_UI_SHOW';
export const COLLABORATOR_UI_HIDE = 'COLLABORATOR_UI_HIDE';

export const COLLABORATOR_USERS_REQUEST = 'COLLABORATOR_USERS_REQUEST';
export const COLLABORATOR_USERS_SUCCESS = 'COLLABORATOR_USERS_SUCCESS';
export const COLLABORATOR_USERS_FAIL = 'COLLABORATOR_USERS_FAIL';

export const COLLABORATOR_INVITATION_REQUEST = 'COLLABORATOR_INVITATION_REQUEST';
export const COLLABORATOR_INVITATION_SUCCESS = 'COLLABORATOR_INVITATION_SUCCESS';
export const COLLABORATOR_INVITATION_FAIL = 'COLLABORATOR_INVITATION_FAIL';
