export const FEEDBACK_LIST_REQUEST = 'FEEDBACK_LIST_REQUEST';
export const FEEDBACK_LIST_SUCCESS = 'FEEDBACK_LIST_SUCCESS';
export const FEEDBACK_LIST_FAIL = 'FEEDBACK_LIST_FAIL';
export const FEEDBACK_LIST_RESET = 'FEEDBACK_LIST_RESET';

export const FEEDBACK_CREATE_REQUEST = 'FEEDBACK_CREATE_REQUEST';
export const FEEDBACK_CREATE_SUCCESS = 'FEEDBACK_CREATE_SUCCESS';
export const FEEDBACK_CREATE_FAIL = 'FEEDBACK_CREATE_FAIL';
export const FEEDBACK_CREATE_RESET = 'FEEDBACK_CREATE_RESET';

export const FEEDBACK_REPLY_REQUEST = 'FEEDBACK_REPLY_REQUEST';
export const FEEDBACK_REPLY_RESET = 'FEEDBACK_REPLY_RESET';

export const FEEDBACK_ACTIVE_REQUEST = 'FEEDBACK_ACTIVE_REQUEST';
export const FEEDBACK_ACTIVE_RESET = 'FEEDBACK_ACTIVE_RESET';
