export const MEDIA_LIST_REQUEST = 'MEDIA_LIST_REQUEST';
export const MEDIA_LIST_SUCCESS = 'MEDIA_LIST_SUCCESS';
export const MEDIA_LIST_FAIL = 'MEDIA_LIST_FAIL';
export const MEDIA_LIST_RESET = 'MEDIA_LIST_RESET';

export const MEDIA_DETAILS_REQUEST = 'MEDIA_DETAILS_REQUEST';
export const MEDIA_DETAILS_SUCCESS = 'MEDIA_DETAILS_SUCCESS';
export const MEDIA_DETAILS_FAIL = 'MEDIA_DETAILS_FAIL';
export const MEDIA_DETAILS_RESET = 'MEDIA_DETAILS_RESET';

export const MEDIA_CREATE_REQUEST = 'MEDIA_CREATE_REQUEST';
export const MEDIA_CREATE_SUCCESS = 'MEDIA_CREATE_SUCCESS';
export const MEDIA_CREATE_FAIL = 'MEDIA_CREATE_FAIL';
export const MEDIA_CREATE_RESET = 'MEDIA_CREATE_RESET';
export const MEDIA_CREATE_PARENT = 'MEDIA_CREATE_PARENT';
export const MEDIA_CREATE_PARENT_RESET = 'MEDIA_CREATE_PARENT_RESET'
export const MEDIA_CREATE_SHOW = 'MEDIA_CREATE_SHOW'
export const MEDIA_CREATE_HIDE = 'MEDIA_CREATE_HIDE'

export const MEDIA_UPDATE_REQUEST = 'MEDIA_UPDATE_REQUEST';
export const MEDIA_UPDATE_SUCCESS = 'MEDIA_UPDATE_SUCCESS';
export const MEDIA_UPDATE_FAIL = 'MEDIA_UPDATE_FAIL';
export const MEDIA_UPDATE_RESET = 'MEDIA_UPDATE_RESET';

export const MEDIA_DELETE_REQUEST = 'MEDIA_DELETE_REQUEST';
export const MEDIA_DELETE_SUCCESS = 'MEDIA_DELETE_SUCCESS';
export const MEDIA_DELETE_FAIL = 'MEDIA_DELETE_FAIL';
export const MEDIA_DELETE_RESET = 'MEDIA_DELETE_RESET';
