export const MEDIA_DETAILS_REQUEST = 'MEDIA_DETAILS_REQUEST'
export const MEDIA_DETAILS_SUCCESS = 'MEDIA_DETAILS_SUCCESS'
export const MEDIA_DETAILS_FAIL = 'MEDIA_DETAILS_FAIL'
export const MEDIA_DETAILS_RESET = 'MEDIA_DETAILS_RESET'
