// Notification from database/old
export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL';
export const NOTIFICATION_LIST_RESET = 'NOTIFICATION_LIST_RESET';

// Delete all notificaion from backend database
export const NOTIFICATIONS_DELETE_REQUEST = 'NOTIFICATIONS_DELETE_REQUEST';
export const NOTIFICATIONS_DELETE_SUCCESS = 'NOTIFICATIONS_DELETE_SUCCESS';
export const NOTIFICATIONS_DELETE_FAIL = 'NOTIFICATIONS_DELETE_FAIL';
export const NOTIFICATIONS_DELETE_RESET = 'NOTIFICATIONS_DELETE_RESET';

// Clear all notifications from frontend storage
export const NOTIFICATION_LIST_CLEAR = 'NOTIFICATION_LIST_CLEAR';

// Add notification from SSE
export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
