export const PLAYLIST_DETAILS_REQUEST = 'PLAYLIST_DETAILS_REQUEST';
export const PLAYLIST_DETAILS_SUCCESS = 'PLAYLIST_DETAILS_SUCCESS';
export const PLAYLIST_DETAILS_FAIL = 'PLAYLIST_DETAILS_FAIL';
export const PLAYLIST_DETAILS_RESET = 'PLAYLIST_DETAILS_RESET';
