export const REVIEW_DETAILS_REQUEST = 'REVIEW_DETAILS_REQUEST';
export const REVIEW_DETAILS_SUCCESS = 'REVIEW_DETAILS_SUCCESS';
export const REVIEW_DETAILS_FAIL = 'REVIEW_DETAILS_FAIL';
export const REVIEW_DETAILS_RESET = 'REVIEW_DETAILS_RESET';
