export const SEARCH_PROJECT_NAME = 'SEARCH_PROJECT_NAME';
export const SEARCH_PROJECT_RESET = 'SEARCH_PROJECT_RESET';

export const SEARCH_REVIEW_NAME = 'SEARCH_REVIEW_NAME';
export const SEARCH_REVIEW_RESET = 'SEARCH_REVIEW_RESET';

export const SEARCH_FILTER_PROJECT_SHOW = 'SEARCH_FILTER_PROJECT_SHOW';
export const SEARCH_FILTER_PROJECT_HIDE = 'SEARCH_FILTER_PROJECT_HIDE';

export const SEARCH_FILTER_PROJECT_CREATED = 'SEARCH_FILTER_PROJECT_CREATED';
export const SEARCH_FILTER_PROJECT_CREATED_RESET = 'SEARCH_FILTER_PROJECT_CREATED_RESET';

export const SEARCH_FILTER_PROJECT_COLLABORATED = 'SEARCH_FILTER_PROJECT_COLLABORATED';
export const SEARCH_FILTER_PROJECT_COLLABORATED_RESET = 'SEARCH_FILTER_PROJECT_COLLABORATED_RESET';

export const SEARCH_FILTER_REVIEW_SHOW = 'SEARCH_FILTER_REVIEW_SHOW';
export const SEARCH_FILTER_REVIEW_HIDE = 'SEARCH_FILTER_REVIEW_HIDE';

export const SEARCH_FILTER_REVIEW_CREATED = 'SEARCH_FILTER_REVIEW_CREATED';
export const SEARCH_FILTER_REVIEW_CREATED_RESET = 'SEARCH_FILTER_REVIEW_CREATED_RESET';

export const SEARCH_FILTER_REVIEW_COLLABORATED = 'SEARCH_FILTER_REVIEW_COLLABORATED';
export const SEARCH_FILTER_REVIEW_COLLABORATED_RESET = 'SEARCH_FILTER_REVIEW_COLLABORATED_RESET';
