export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_UPLOAD_IMAGE_REQUEST = 'USER_UPLOAD_IMAGE_REQUEST';
export const USER_UPLOAD_IMAGE_SUCCESS = 'USER_UPLOAD_IMAGE_SUCCESS';
export const USER_UPLOAD_IMAGE_FAIL = 'USER_UPLOAD_IMAGE_FAIL';
export const USER_UPLOAD_IMAGE_RESET = 'USER_UPLOAD_IMAGE_RESET';

export const USER_PASSWORD_RESET_EMAIL_REQUEST =
  'USER_PASSWORD_RESET_EMAIL_REQUEST';
export const USER_PASSWORD_RESET_EMAIL_SUCCESS =
  'USER_PASSWORD_RESET_EMAIL_SUCCESS';
export const USER_PASSWORD_RESET_EMAIL_FAIL = 'USER_PASSWORD_RESET_EMAIL_FAIL';
export const USER_PASSWORD_RESET_EMAIL_RESET =
  'USER_PASSWORD_RESET_EMAIL_RESET';

export const USER_PASSWORD_RESET_CONFIRM_REQUEST =
  'USER_PASSWORD_RESET_CONFIRM_REQUEST';
export const USER_PASSWORD_RESET_CONFIRM_SUCCESS =
  'USER_PASSWORD_RESET_CONFIRM_SUCCESS';
export const USER_PASSWORD_RESET_CONFIRM_FAIL =
  'USER_PASSWORD_RESET_CONFIRM_FAIL';
export const USER_PASSWORD_RESET_CONFIRM_RESET =
  'USER_PASSWORD_RESET_CONFIRM_RESET';

export const USER_INVITE_GET_EMAIL_REQUEST = 'USER_INVITE_GET_EMAIL_REQUEST';
export const USER_INVITE_GET_EMAIL_SUCCESS = 'USER_INVITE_GET_EMAIL_SUCCESS';
export const USER_INVITE_GET_EMAIL_FAIL = 'USER_INVITE_GET_EMAIL_FAIL';
export const USER_INVITE_GET_EMAIL_RESET = 'USER_INVITE_GET_EMAIL_RESET';

export const USER_INVITE_ACCEPT_REQUEST = 'USER_INVITE_ACCEPT_REQUEST';
export const USER_INVITE_ACCEPT_SUCCESS = 'USER_INVITE_ACCEPT_SUCCESS';
export const USER_INVITE_ACCEPT_FAIL = 'USER_INVITE_ACCEPT_FAIL';
export const USER_INVITE_ACCEPT_RESET = 'USER_INVITE_ACCEPT_RESET';
