# Generated by Django 3.2.6 on 2022-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='msg_type',
            field=models.IntegerField(choices=[(1, 'project'), (2, 'review'), (3, 'feedback'), (0, 'info'), (4, 'deepgram')], default=0),
        ),
    ]
