# Generated by Django 3.2.5 on 2021-09-15 19:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0004_auto_20210915_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='collaborators',
            field=models.ManyToManyField(blank=True, null=True, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
