# Generated by Django 3.2.5 on 2021-09-15 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0005_alter_review_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='collaborators',
            field=models.ManyToManyField(related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
