# Generated by Django 3.2.5 on 2021-09-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_id',
        ),
    ]
