# Generated by Django 3.2.5 on 2021-09-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_rename_user_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
