# Generated by Django 3.2.5 on 2021-09-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0011_rename_user_id_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image_url',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
