# Generated by Django 3.2.6 on 2021-10-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_auto_20211017_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='resource_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
