# Generated by Django 3.2.6 on 2021-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0017_asset_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
