# Generated by Django 3.2.6 on 2021-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0018_asset_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
