# Generated by Django 3.2.6 on 2021-11-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0019_project_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='number_of_collaborator',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='number_of_media',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
